### ISSUE TITLE
nan on GTX-1080

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1651]
Using the OpenCL platform of the `openmm` 7.1.0 `dev` build (built with CUDA 8.0), I've noticed that GTX-1080 (NVIDIA linux driver 367.35; only CUDA 7.5 installed) causes simulations on the `OpenCL` platform to rapidly terminate with `nan`, while other graphics cards are fine.

Has anyone else observed this?

**Comment by jchodera** [comment]
Surprisingly, this appears to be due to the `MonteCarloBarostat`. Disabling the barostat results in normal operation. Enabling the barostat and it's `nan` city in no time at all. This seems to work fine on GTX-680s (driver 352.39) and GTX-TITANs (driver 352.39).

See the attached demonstration script and input files. Uncommenting the following line will disable the barostat, which works fine on the GTX-1080 (driver 367.35):
```python
#pressure = None # Uncomment this to disable barostat
```
[gtx-1080-issue.zip](https://github.com/pandegroup/openmm/files/549329/gtx-1080-issue.zip)

**Comment by jchodera** [comment]
To install the 7.1.0 `dev` build (if you want to use the `conda` package):
```bash
# clean cache
conda clean -pltis --yes
# install dev build
conda install -c omnia/label/dev openmm==7.1.0
```

**Comment by jchodera** [comment]
I should note these results were using the `OpenCL` `Platform`; since this machine only has CUDA 7.5 installed, the `CUDA` platform is unavailable and the `OpenCL` platform is selected.

**Comment by jchodera** [comment]
Could this somehow be related to the fact that the GTX-1080 is CUDA compute capability 6.x? Does anyone else have access to other 6.x cards (Nvidia Titan X, GeForce GTX 1080, GTX 1070, GTX 1060, GTX 1050 Ti, GTX 1050) they could try this example on?

**Comment by peastman** [comment]
I'll see if I can reproduce this on a Pascal Titan X.  My first guess is that it might be an incompatibility between the GPU, CUDA 7.5 (which predates Pascal GPUs and doesn't officially support them), and the newer drivers.  If you upgrade to CUDA 8 does the error go away?

**Comment by jchodera** [comment]
> If you upgrade to CUDA 8 does the error go away?

I don't have root on this machine, but I have put in a request to have CUDA 8.0 installed.

NVIDIA claims that [GTX-1080 support was added in `linux` driver 367.27](http://www.nvidia.com/download/driverResults.aspx/104284/en-us). This machine was using 367.35, which was released after GTX-1080 support was added.

Question: Will the CUDA 7.5 libraries still be used even by the `OpenCL` platform? Or is the CUDA Toolkit ignored in that case, with the OpenMM build interacting directly with the driver?

**Comment by peastman** [comment]
I was able to reproduce this with CUDA 8.0, so that doesn't seem to be the problem.  I also verified that it only happens with OpenCL, not CUDA.  Investigating...

**Comment by peastman** [comment]
I'm still trying to figure out what's going on, but I think I've found a workaround.  The problem seems to be related to the @#$%! PME stream.  If I specify `{'OpenCLDisablePmeStream':'true'}` when creating the Context, the error goes away.

**Comment by jchodera** [comment]
> If I specify {'OpenCLDisablePmeStream':'true'} when creating the Context, the error goes away.

Awesome! Thanks for the workaround!

**Comment by jchodera** [comment]
I'm still seeing sporadic `nan`s when the barostat is enabled even with the workaround, though they are at reduced frequency.

**Comment by peastman** [comment]
Hmph.

**Comment by kyleabeauchamp** [comment]
I have a GTX 1060 (GB) with CUDA8 and I was able to run to completion:

```
iteration    97 /   100 : energy = -633920.2096799347 kJ/mol
iteration    98 /   100 : energy = -632305.9093753137 kJ/mol
iteration    99 /   100 : energy = -634031.3099149512 kJ/mol
```

**Comment by kyleabeauchamp** [comment]
I ran it twice, but I don't know what nan frequency to expect.

**Comment by jchodera** [comment]
Wow, without the pressure set to None? Which card and drivers do you have, and how did you install openmm?

**Comment by kyleabeauchamp** [comment]
This is a manual build of latest git master.

```
:~/src/openmm/omm-build/python$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

:~/src/openmm/omm-build/python$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
:~/src/openmm/omm-build/python$ nvidia-smi 
Wed Oct 26 19:47:20 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 0000:01:00.0      On |                  N/A |
|  0%   43C    P8    11W / 180W |    788MiB /  6069MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1106    G   /usr/lib/xorg/Xorg                             331MiB |
|    0      1919    G   compiz                                          91MiB |
|    0      2199    G   /usr/lib/firefox/firefox                         2MiB |
|    0      3116    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    40MiB |
|    0      5825    G   /usr/lib/xorg/Xorg                             125MiB |
|    0      5939    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    37MiB |
|    0     25449    C   ~/anaconda3/bin/python               123MiB |
+-----------------------------------------------------------------------------+
```

**Comment by kyleabeauchamp** [comment]
I ran the script you provided without modification

**Comment by kyleabeauchamp** [comment]
Running on latest anaconda3 (py35)

**Comment by peastman** [comment]
In my testing it's quite variable.  Sometimes it happens on the very first iteration, other times it run through all 100 iterations without failing.  And it seems to go in waves.  There are times when it consistently fails in the first 10 iterations, and other times when it goes all the way without failing several times in a row.  I really don't know why.  It makes it hard to debug!

**Comment by jchodera** [comment]
Sadly, I don't have a more robust test case yet. I'll see if fiddling with the simulation parameters can somehow increase the failure rate.

**Comment by peastman** [comment]
I tried several more times, but I haven't been able to reproduce this with the PME stream disabled.  Since that still fails for you, could you try a couple of other tests?  First, try setting 'UseCpuPme' to 'true'.  Does it ever fail with that?  Second, try setting the nonbonded method to CutoffPeriodic.  Does that fail?

**Comment by peastman** [comment]
> I ran the script you provided without modification

Make sure you're using the OpenCL platform.  The original script didn't specify a platform, so if you haven't modified it, you're probably using CUDA.

**Comment by jchodera** [comment]
Thanks for trying, @peastman! I'll do some more testing once our hardware comes back online. (It's offline now for CUDA 8.0 and driver upgrades.)

**Comment by kyleabeauchamp** [comment]
OK, I manually set the platform to OpenCL and the script died after the second run: 

```
iteration    18 /   100 : energy = -631392.0435686307 kJ/mol
iteration    19 /   100 : energy = -631395.3048638394 kJ/mol
iteration    20 /   100 : energy = -631382.2855832344 kJ/mol
iteration    21 /   100 : energy = -632079.3594053807 kJ/mol
iteration    22 /   100 : energy = -632315.016984256 kJ/mol
Traceback (most recent call last):
  File "gtx-1080-issue.py", line 73, in <module>
    integrator.step(nsteps)
  File "~/anaconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 15116, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Particle coordinate is nan
```

**Comment by jchodera** [comment]
@peastman : Have you had any luck tracking this down?

**Comment by peastman** [comment]
I've never been able to reproduce this with the PME stream disabled.  When we left off the discussion, I had suggested some things for you to try, and you said you were going to do more testing when your hardware came back online.

**Comment by jchodera** [comment]
Still no hardware here. Sorry.

Maybe if we chase down the PME stream error first?

**Comment by jchodera** [comment]
I think this was fixed by #1715! I was able to run the test case several times on a GTX-1080 with zero `nan` encounters!

**Comment by peastman** [comment]
I'm still seeing the error.  Perhaps you just got (un)lucky and it happened to run all the way through without failing?

**Comment by jchodera** [comment]
D'oh. Which GPU, driver, and platform were you using? Also GTX-1080?

**Comment by peastman** [comment]
Titan X Pascal, 367.48 driver.  Did you try several times?  Since it's not deterministic, it will sometimes make it all the way just by chance.

**Comment by jchodera** [comment]
I had tried three times on GTX-1080, 367.48 driver, CUDA 8.0. I'll run it in a loop and see if I can run into a failure.
