### ISSUE TITLE
Unable to compile CUDA code for amd.py

### ISSUE THREAD

**Issue by lvotapka** [pandegroup/openmm#2116]
Hello All,

I'm trying to use the aMD integrator, and I'm using commands similar to the following:

`
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
prmtop = AmberPrmtopFile('holo.parm7')
inpcrd = AmberInpcrdFile('holo.rst7')
alpha = 0.02 * kilojoules_per_mole
E = -339256 * kilojoules_per_mole
system2 = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
        constraints=HBonds)
platform = Platform.getPlatformByName('CUDA')
properties = {'CudaDeviceIndex': '0', 'CudaPrecision': 'mixed'}
integrator2 = AMDIntegrator(0.002*picoseconds, alpha, E)

simulation2 = Simulation(prmtop.topology, system2, integrator2, platform, properties)

simulation2.context.setPositions(inpcrd.positions)
simulation2.context.setVelocitiesToTemperature(300*kelvin)

if inpcrd.boxVectors is not None:
    simulation2.context.setPeriodicBoxVectors(*inpcrd.boxVectors)

simulation2.minimizeEnergy()
`

When I run, I get the following error:

`Traceback (most recent call last):
  File "test_amd2.py", line 22, in <module>
    simulation2.minimizeEnergy()
  File "/home/lvotapka/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 128, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/lvotapka/miniconda2/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 2743, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
Exception: Error launching CUDA compiler: 512
/tmp/openmmTempKernel0x559e637a6580_12858.cu(732): error: no operator "-" matches these operands
            operand types are: double3 - const mixed

/tmp/openmmTempKernel0x559e637a6580_12858.cu(743): error: no operator "-" matches these operands
            operand types are: double3 - const mixed

/tmp/openmmTempKernel0x559e637a6580_12858.cu(727): warning: variable "gaussianIndex" was declared but never referenced

/tmp/openmmTempKernel0x559e637a6580_12858.cu(728): warning: variable "uniformIndex" was declared but never referenced

2 errors detected in the compilation of "/tmp/tmpxft_00003250_00000000-7_openmmTempKernel0x559e637a6580_12858.cpp1.ii".
`
I'm pretty sure that the problem has to do with line 66 in amd.py. For some reason, the expression compiler thinks that 'alpha' and 'E' need to be treated as double3 variables.

Is there an easy fix to this, or might there be something wrong with the CustomIntegrator expression compiler?

**Comment by jchodera** [comment]
Can you let us know which version of OpenMM you have installed (and how you installed it), as well as package up the input files into a ZIP archive and post it here?

**Comment by lvotapka** [comment]
Sure, I'm using OpenMM 7.1.1, which I installed from source. I can give other information about the installation if necessary.

Here is the zip file of the input files:
[test_amd.zip](https://github.com/pandegroup/openmm/files/2181527/test_amd.zip)

**Comment by peastman** [comment]
Could you try using OpenMM 7.2.2?  As a first step in debugging it, we should make sure this isn't a problem that has already been fixed in a more recent version.

**Comment by lvotapka** [comment]
My mistake, it was actually OpenMM 7.2.1. 

I know you said 7.2.2, but I pulled OpenMM 7.3.0, and I still get the exact same error.

**Comment by peastman** [comment]
I verified that I can reproduce the error.  I'm investigating now.

**Comment by lvotapka** [comment]
Thank you for resolving this issue so quickly, @peastman and @jchodera. 
For my own future reference, where is the best place to obtain source code for releases if not this git repo?

**Comment by peastman** [comment]
You can download them from https://github.com/pandegroup/openmm/releases.

**Comment by lvotapka** [comment]
OK thanks again.

**Comment by lvotapka** [comment]
Sorry to bug you guys again, but I downloaded the OpenMM 7.2.2 release, applied the bugfix, then recompiled and tested my script.

Unfortunately, the script failed again, this time with a slightly different error, but it looks similar.

Traceback (most recent call last):
  File "test_amd.py", line 22, in <module>
    simulation.minimizeEnergy()
  File "/home/lvotapka/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 128, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/lvotapka/miniconda2/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 2743, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
Exception: Error launching CUDA compiler: 512
/tmp/openmmTempKernel0x55838133d8f0_13307.cu(730): error: no operator "-" matches these operands
            operand types are: const mixed - double3

/tmp/openmmTempKernel0x55838133d8f0_13307.cu(734): error: no operator "-" matches these operands
            operand types are: double - double3

/tmp/openmmTempKernel0x55838133d8f0_13307.cu(745): error: no operator "-" matches these operands
            operand types are: const mixed - double3

/tmp/openmmTempKernel0x55838133d8f0_13307.cu(749): error: no operator "-" matches these operands
            operand types are: double - double3

/tmp/openmmTempKernel0x55838133d8f0_13307.cu(760): error: no operator "-" matches these operands
            operand types are: const mixed - double3

/tmp/openmmTempKernel0x55838133d8f0_13307.cu(764): error: no operator "-" matches these operands
            operand types are: double - double3

/tmp/openmmTempKernel0x55838133d8f0_13307.cu(723): warning: variable "gaussianIndex" was declared but never referenced

/tmp/openmmTempKernel0x55838133d8f0_13307.cu(724): warning: variable "uniformIndex" was declared but never referenced

6 errors detected in the compilation of "/tmp/tmpxft_00003435_00000000-7_openmmTempKernel0x55838133d8f0_13307.cpp1.ii".

As you can see, this time the double3 seems to be conflicting in some other locations, maybe with some other types of integrators?

**Comment by peastman** [comment]
This isn't a patch to 7.2.2.  The error was created by a new feature in 7.3.  7.2.2 already works fine as it is.

**Comment by lvotapka** [comment]
Ah ok, I get it now. Everything seems to work fine at this time.
